{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cpa.fullname" . }}-web
  labels:
    {{- include "cpa.labels" . | nindent 4 }}
type: Opaque
stringData:
  AUTH_SECRET: {{ default (randAlphaNum 48) .Values.secrets.authSecret | quote }}
{{- end }}
